### PR TITLE
reuse inner function when recursive

### PR DESCRIPTION
**Pull request by futurist**
Hi, I want to create a similar tool until I saw this, looking into the code and found it's better to have inner function reused, at least it's reduce function calls for a large view tree building.

### CODE REVIEW

**Comment by lukejacksonn** [comment]
Hey 👋 looks cool. Have you managed to run any perf tests on it? I am curious to see the gains.

**Comment by futurist** [comment]
Sure, for 2nd commit, please check

https://jsperf.com/check-is-array

isArrayRef is 31% faster than isArrayFunction (in Firefox, since V8 will optimize then inline the function, which will transform the test result), it's obvious that invoke a function each time is slow.

For 1st commit, please check

https://jsperf.com/ijk-pr-22

AfterPR is 18% faster than BeforePR, in Chrome, 17% faster in Firefox.

Moreover, I believe 1st commit allow more nested children since it has lower stack size in each recursive. (not tested, but it is not worse at least!)

**Comment by lukejacksonn** [comment]
Thanks for taking the time to do this 💯 the changes make sense, perf has increased and tests are passing; so I am happy to merge this and do a release as soon as I get time.

**Comment by lukejacksonn** [comment]
Thats for the contribution @futurist 🙇 let me know if you have any other bright ideas!

**Comment by lukejacksonn** [comment]
Master has been published to npm: https://unpkg.com/ijk@0.24.0/index.js

**Pull request merged**
